# Generated by Django 6.0 on 2026-01-28 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=100, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('desc', models.TextField(null=True)),
                ('percent', models.IntegerField(null=True)),
                ('progress', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='skill_items',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
