# Generated by Django 6.0 on 2026-01-28 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_skill_skill_items_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='progress',
        ),
    ]
