# Generated by Django 6.0 on 2026-02-18 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_skill_url_skill_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='certificate',
            field=models.FileField(null=True, upload_to='skill cetificate'),
        ),
    ]
