# Generated by Django 6.0 on 2026-01-30 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_skill_tools'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testinomial',
        ),
        migrations.AddField(
            model_name='skill',
            name='url',
            field=models.URLField(help_text='Enter the complete URL', max_length=500, null=True),
        ),
    ]
