# Generated by Django 6.0 on 2026-01-30 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_testinomial_skill_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='url',
        ),
        migrations.AddField(
            model_name='skill',
            name='certificate',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
