# Generated by Django 6.0 on 2026-02-18 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_skill_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='certificate',
            field=models.ImageField(blank=True, null=True, upload_to='skill certficate'),
        ),
    ]
