# Generated by Django 6.0 on 2026-02-18 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_skill_certificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testinomial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('role', models.CharField(max_length=200, null=True)),
                ('company', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('feedback', models.TextField(null=True)),
                ('image', models.ImageField(null=True, upload_to='testinomial_image')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
